### ISSUE TITLE
How to contribute to the project.

### ISSUE THREAD

**Issue by agustif** [zedwarth/igdbex#1]
Hi Seth! I wanted to email you to not create a GH Issue for this, but couldn't find how. So here we are.

I was thinking in doing myself a IGDB API Elixir Library, let me know if you would like some junior help on this, I have the time to dedicate to it at least!

Let me know what are your plans on future development/roadmap so I can integrate in the project without stepping into your foot.

**Comment by agustif** [comment]
So should I just start my own lib right?

**Comment by zedwarth** [comment]
Crap, I sorry, man.  I should have responded sooner.

I don't have time to work on this now, so don't worry on stepping on my foot or anything with it.

If you want to use this as a base you're more than welcome to.

(BTW, you can find my email in my commit messages.)

**Comment by agustif** [comment]
Oh cool! no problem man, it's open source, I'm thankful you answered at all. So I will give it a try if I do something meaningful with your code might open PR.

Have a nice day!! And thanks for the email tip, will get in touch!
